# Generated by Django 4.1.1 on 2022-09-23 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Crsytal',
            new_name='Crystal',
        ),
    ]
