# Generated by Django 4.1.1 on 2022-09-23 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_crsytal_crystal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cleanse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('method', models.CharField(choices=[('S', 'Sunlight'), ('M', 'Moonlight'), ('W', 'Water'), ('I', 'Incense')], default='M', max_length=1)),
                ('crystal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.crystal')),
            ],
        ),
    ]
