# Generated by Django 4.1.1 on 2022-09-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_cleanse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='cleanse',
            name='date',
            field=models.DateField(verbose_name='Cleansing Date'),
        ),
    ]
