# Generated by Django 4.1.1 on 2022-09-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_blog_alter_cleanse_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='crystal',
            name='blogs',
            field=models.ManyToManyField(to='main_app.blog'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(max_length=5000),
        ),
    ]
